global using Arkn.Results;
global using AIFeed.Api.Infrastructure.Persistence;
global using AIFeed.Api.Infrastructure.Sources;
global using Microsoft.AspNetCore.Builder;
global using Microsoft.AspNetCore.Http;
global using Microsoft.AspNetCore.RateLimiting;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.DependencyInjection;
global using System.Threading.RateLimiting;
